### ISSUE TITLE
Incompatibility with Carpet

### ISSUE THREAD

**Issue by furtabs** [JamiesWhiteShirt/reach-entity-attributes#1]

**Comment by apace100** [comment]
Can confirm, after a user [created an issue about this on my mod's GitHub](https://github.com/apace100/origins-fabric/issues/18), I investigated. Crashes on world start with only Fabric API, Carpet, and this library installed.

Crash Log here: https://pastebin.com/RnHfhUHJ

**Comment by Nathan22211** [comment]
I believe genoben fixed this a few months ago
