### ISSUE TITLE
Attack range really used?

### ISSUE THREAD

**Issue by charlyb01** [JamiesWhiteShirt/reach-entity-attributes#11]
I want to implement this library in my mod, but during my test of the lib, it really seems that players can attack in the whole reach, even if the attack range is smaller. I haven't yet found where the problem could be.
Moreover, the base value of the attributes are set to 0 but it seems that they are initialized to 3.0 and 4.5. I haven't been able to find out where it was initialized ^^

**Comment by ChloeDawn** [comment]
The attributes are implemented additively, so you need to use negative values to subtract from the base values
https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/58c0871fba044d21f028e3cdf78f66dd01fa323f/src/main/java/com/jamieswhiteshirt/reachentityattributes/ReachEntityAttributes.java#L28
https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/58c0871fba044d21f028e3cdf78f66dd01fa323f/src/main/java/com/jamieswhiteshirt/reachentityattributes/ReachEntityAttributes.java#L38

**Comment by charlyb01** [comment]
Oh yes alright, I've seen this but I didn't compute the information I guess, thanks!
About what I said first (ability to attack within the reach instead of attack range), can you confirm that I'm right? Or maybe I just didn't use/understand it well too. Anyway, thanks for your time

**Comment by charlyb01** [comment]
I made a break and came back and of course, I understood what I did wrong ^^
If I could make a suggestion: change the way attributes are handled. I mean either not making it additive, or delete the `baseValue` of the methods and replace it by a static value that people can access from outside of the mod because currently, we need to use a magic number to refer to the baseValue. I hope it was clear enough, and I can close this issue btw
