### ISSUE TITLE
Attack Reach & Reach attributes don't match Attack Damage and Attack Speed attributes on tools

### ISSUE THREAD

**Issue by CammiePone** [JamiesWhiteShirt/reach-entity-attributes#13]
Attack Damage and Attack Speed attributes are green, and show the total attribute value on the tooltip, but Attack Reach and Reach show as the normal blue.

Is there anything that can be done to fix that?

Reach Entity Attributes: 2.1.1
Minecraft: 1.17.1

**Comment by ChloeDawn** [comment]
How are you applying the attribute to your item?

**Comment by CammiePone** [comment]
You have yet to behold the horrors that I have wrought upon this world

![image](https://user-images.githubusercontent.com/16853086/136481516-c511baf5-809c-4962-a1eb-d9b706cac811.png)

**ItemStackMixin:**
https://github.com/CammiePone/Cammies-Combat-Tweaks/blob/1.17-dev/src/main/java/dev/cammiescorner/combattweaks/core/mixin/ItemStackMixin.java

**ResourceReloadListener:**
https://github.com/CammiePone/Cammies-Combat-Tweaks/blob/1.17-dev/src/main/java/dev/cammiescorner/combattweaks/common/data/AttributeReloadListener.java

**Trident Attribute Override JSON:**
https://github.com/CammiePone/Cammies-Combat-Tweaks/blob/1.17-dev/src/main/resources/data/minecraft/attribute_overrides/trident.json

**Comment by ChloeDawn** [comment]
After reviewing the game code, I've decided that it would be out of scope for this library to make the changes necessary for this re-color. To support it is a lot of work and the mixins would be very fragile. It doesn't make sense for a stable library to include it IMO. However, you should be able to implement it in your own code just fine if you wish. You can find the logic in ItemStack's tooltip method.

**Comment by CammiePone** [comment]
Alright, wasn't sure if it would be better suited to the library itself, or if it should be implemented myself. Just dunno how many other mods would try and implement it themselves, and how well they would implement it themselves.
