### ISSUE TITLE
[Crash] ReachEntityAttributes class not present on server 

### ISSUE THREAD

**Issue by Tiviacz1337** [JamiesWhiteShirt/reach-entity-attributes#27]
Hi, class ReachEntityAttributes class seems to not be present on server side.
Fabric 1.19.4 - 0.14.19
Fabric API 0.76.0+1.19.4
Reach Entity Attributes 2.3.2

Crashlog: https://pastebin.com/QEmMUyNN

**Comment by ChloeDawn** [comment]
The version of Traveler's Backpack you are using does not include Reach Entity Attributes in its file.
Make sure you are on the latest version, and if you still experience this crash, report it to them.

**Comment by Tiviacz1337** [comment]
include modImplementation("com.jamieswhiteshirt:reach-entity-attributes:${project.reach_entity_attributes_version}")

I've put it in build.gradle, game crashes only on server though, client works fine
