### ISSUE TITLE
MINECRAFT 1.20.4 VERSION NO LONGER WORKS

### ISSUE THREAD

**Issue by Zigned3090** [JamiesWhiteShirt/reach-entity-attributes#32]
when my mod updated to minecraft version 1.20.4, it no longer worked.

**Comment by thomasglasser** [comment]
This is very unhelpful lol, doesn't explain why at all

**Comment by thomasglasser** [comment]
`Critical injection failure: Constant modifier method getActualReachDistance(F)F in mixins.reach-entity-attributes.json:client.ClientPlayerInteractionManagerMixin from mod reach-entity-attributes failed injection check`

**Comment by thomasglasser** [comment]
This is the crash cause, should be enough info

**Comment by Zigned3090** [comment]
@thomasglasser so, what should i do?

**Comment by thomasglasser** [comment]
Correct the mixin, it's likely the args changed. I'll look into it

**Comment by thomasglasser** [comment]
`ClientPlayerInteractionManager` now redirects to `PlayerEntity` to check the reach, which makes it no longer clientside and removes the context of the player

**Comment by thomasglasser** [comment]
The mojmaps of the new static method in `PlayerEntity`:
```java
public static float getPickRange(boolean bl) {
        return bl ? 5.0F : 4.5F;
    }

**Comment by Zigned3090** [comment]
@thomasglasser oaky, but it's a static method, i cant get the entity attribut in the method(

**Comment by thomasglasser** [comment]
You'll just have to mixin everywhere the static method is called and change the value there

**Comment by ChloeDawn** [comment]
I am currently on vacation, this will be fixed in mid-January

**Comment by AlphaMode** [comment]
Any updates on this? Its blocking my mod development.

**Comment by ChloeDawn** [comment]
2.5.0 for 1.20.4 is now on Maven
