### ISSUE TITLE
The chests will stay open

### ISSUE THREAD

**Issue by SistrScarlet** [JamiesWhiteShirt/reach-entity-attributes#9]
Minecraft: 1.16.5
ReachEntityAttributes: 1.1.0

It is triggered when you open a chest at least 2 meters away from it and then wait for a few seconds.
Other than its appearance, it doesn't seem to do any harm.

The reason is that the value of baseReachDistance passed to ReachEntityAttributes.getPlayersWithinReach() in getPlayersAccountingForReach() of ChestBlockEntityMixin is not square. I think this is the cause.

I use DeepL translation to write my sentences, so I apologize if there are any strange parts.

**Comment by ChloeDawn** [comment]
Fixed in 1.1.1 (1.16) and 2.0.1 (1.17)
